version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./default-v3.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemp
  php:
    image: sergiutot/phpfixed:v1.0
    volumes:
      - ./:/code
    networks:
      - lemp
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-storage-compose:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sup3Rp4sS
    networks:
      - lemp

volumes:
  mysql-storage-compose:

networks:
  lemp:
